@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook --> UniquePersonList
AddressBook --> UniqueTagList
AddressBook --> UniqueTimedEventList

UniqueTagList --> "*" Tag
UniquePersonList --> "*" Person
UniqueTimedEventList --> "*" TimedEvent

Person --> "*" Tag

' Person attributes
Person --> Name
Person --> Phone
Person --> Email
Person --> StudentId
Person --> ClassNumber
Person --> Github
Person --> ProjectTeam
Person --> Progress
Person --> Repository

' TimedEvent design
abstract class TimedEvent
class Assignment
Assignment --|> TimedEvent
TimedEvent *--> Name
@enduml
